[package]
name = "eiga"
version = "0.1.0"
edition = "2018"

[dependencies]
eiga_builder_derive = { path = "eiga_builder_derive" }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
ureq = { version = "2.4.0", features = ["json"] }
url = "2.2.2"

[dev-dependencies]
httpmock = "0.6.6"
